# Generated by Django 3.2.9 on 2022-01-31 16:40

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField(max_length=15, null=True, verbose_name=app.models.User)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Procurement_Manager', 'Procurement_Manager'), ('Employee', 'Employee')], max_length=50, null=True)),
                ('department', models.CharField(choices=[('Finance', 'Finance'), ('Human Resource', 'Human Resource'), ('Marketing', 'Marketing')], max_length=15, null=True, verbose_name=app.models.User)),
                ('username', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
