# Generated by Django 3.2.9 on 2022-02-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_staff',
            name='role',
        ),
    ]
