# Generated by Django 3.2.9 on 2022-01-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_requestasset_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestasset',
            name='asset_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
