# Generated by Django 3.2.7 on 2022-02-01 14:49

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField(null=True, verbose_name=app.models.User)),
                ('department', models.CharField(choices=[('Finance', 'Finance'), ('Human Resource', 'Human Resource'), ('Marketing', 'Marketing')], max_length=15, null=True, verbose_name=app.models.User)),
                ('username', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
