# Generated by Django 3.2.9 on 2022-01-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.CreateModel(
            name='Proc_Manager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PROC_MANAGER', 'Proc_Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50, verbose_name='Types'),
        ),
    ]
