# Generated by Django 3.2.9 on 2022-02-01 08:20

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_add_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_staff',
            name='contact',
            field=models.IntegerField(null=True, verbose_name=app.models.User),
        ),
    ]
