# Generated by Django 3.2.7 on 2022-02-01 14:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_staff',
            name='username',
            field=models.CharField(max_length=15, null=True, verbose_name=app.models.User),
        ),
    ]
