# Generated by Django 3.2.9 on 2022-01-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_adminmore_employeemore_proc_managermore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminMore',
            new_name='AdministratorMore',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('PROC_MANAGER', 'Proc_Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50, verbose_name='Types'),
        ),
    ]
