# Generated by Django 3.2.9 on 2022-01-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220128_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('Request', 'Request'), ('Repair', 'Repair')], max_length=50, null=True),
        ),
    ]
