# Generated by Django 3.2.9 on 2022-01-29 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_requestasset_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestasset',
            name='asset_name',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.asset'),
        ),
    ]
