# Generated by Django 3.2.9 on 2022-01-26 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_asset_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Requet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50, null=True)),
                ('Character_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characteristics')),
                ('asset_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.asset')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
