# Generated by Django 3.2.9 on 2022-01-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220126_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requet',
            new_name='Request',
        ),
    ]
