# Generated by Django 3.2.9 on 2022-01-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_requet_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='Character_name',
            new_name='Characteristics',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Character_name',
            new_name='Characteristics',
        ),
        migrations.RemoveField(
            model_name='characteristics',
            name='Character_name',
        ),
    ]
