# Generated by Django 3.2.9 on 2022-01-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220126_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='Characteristics',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Characteristics',
            new_name='category',
        ),
    ]
