# Generated by Django 3.2.9 on 2022-01-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220126_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='request',
            name='category',
        ),
    ]
